FROM osrf/ros:humble-desktop

# Container environment configuration
ENV DEBIAN_FRONTEND=noninteractive \
	LANG=en_US.UTF-8 \
	LC_ALL=en_US.UTF-8 \
	HOME=/root \
	ROS_DISTRO=humble

WORKDIR /root

# Install essential build tools and ROS utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
	lsb-release \
	gnupg \
	curl \
	wget \
	build-essential \
	python3-pip \
	python3-colcon-common-extensions \
	python3-vcstool \
	locales \
	git \
	&& locale-gen en_US.UTF-8 \
	&& update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
	&& rm -rf /var/lib/apt/lists/*

# Create ROS2 workspace structure
RUN mkdir -p /root/ros2_ws/src
COPY tmp_sources/ /root/ros2_ws/src/
WORKDIR /root/ros2_ws

# Install dependencies explicitly
RUN apt-get update && apt-get install -y --no-install-recommends \
	ros-humble-geometry-msgs \
	ros-humble-std-msgs \
	ros-humble-tf2 \
	ros-humble-tf2-ros \
	ros-humble-urdf \
	ros-humble-xacro \
	ros-humble-rviz2 \
	ros-humble-realsense2-description \
	ros-humble-robot-state-publisher \
	ros-humble-joint-state-publisher-gui \
	ros-humble-ros-gz \
	ros-humble-ros-gz-sim \
	ros-humble-ros-gz-bridge \
	&& rm -rf /var/lib/apt/lists/*

# fa il build del workspace ROS2
RUN /bin/bash -lc "source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --symlink-install"

# crea uno script che configura l'ambiente ROS2 e poi esegue il comando passato come argomento
RUN echo '#!/bin/bash' > /entrypoint.sh && \
	echo 'source /opt/ros/humble/setup.bash' >> /entrypoint.sh && \
	echo 'source /root/ros2_ws/install/local_setup.bash' >> /entrypoint.sh && \
	echo 'export GZ_SIM_RESOURCE_PATH=/root/ros2_ws/install/rl_fratomo_description/share:$GZ_SIM_RESOURCE_PATH' >> /entrypoint.sh && \
	echo 'exec "$@"' >> /entrypoint.sh && \
	chmod +x /entrypoint.sh

# Configura l'ambiente ROS2
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc \
	&& echo "source /root/ros2_ws/install/local_setup.bash" >> /root/.bashrc \
	&& echo "source /usr/share/colcon_cd/function/colcon_cd.sh" >> /root/.bashrc \
	&& echo "export _colcon_cd_root=/opt/ros/humble/" >> /root/.bashrc \
	&& echo "export GZ_SIM_RESOURCE_PATH=/root/ros2_ws/install/rl_fratomo_description/share:\$GZ_SIM_RESOURCE_PATH" >> /root/.bashrc

ENTRYPOINT ["/entrypoint.sh"]
WORKDIR /root/ros2_ws
CMD ["/bin/bash", "-i"]
